language: cpp

compiler:
    clang
    gcc
 
before_install:
    sudo apt-get update -q

install:
    sudo apt-get install libqt4-dev libssl-dev cmake

script: 
    rm -rf build
    mkdir -p build
    pushd build
    cmake ..
    make
    popd
